# Competition Subject


## Detail contents

# Load Data

In [2]:
import numpy as np
import pandas as pd

data = pd.read_csv("data/train.csv")
#data = data.reindex(np.random.permutation(data.index)) 
data

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,1,2,23,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,39205.170000,0
1,3,2,34,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,49278.030000,0
2,4,2,23,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,67333.770000,0
3,8,2,37,0,195.00,195.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,64007.970000,0
4,10,2,39,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,117310.979016,0
5,13,2,23,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,87975.750000,0
6,14,2,27,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,94956.660000,0
7,18,2,26,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,251638.950000,0
8,20,2,45,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,101962.020000,0
9,23,2,25,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,356463.060000,0
10,25,2,42,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,125424.060000,0
11,26,2,26,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,75368.520000,0
12,29,2,51,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,122220.090000,0
13,31,2,43,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,118436.970000,0
14,32,2,33,600,1086.48,1952.91,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,95294.130000,0
15,34,2,30,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,104403.870000,0
16,36,2,44,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,117310.979016,0
17,39,2,36,0,55.20,70.95,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,153014.130000,0
18,42,229,55,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,168943.230000,0
19,43,2,28,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,96601.140000,0
20,45,2,23,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,69165.030000,0
21,49,2,27,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,63445.560000,0
22,51,2,35,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,117310.979016,0
23,54,2,54,0,117.75,122.25,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,59575.620000,0
24,56,2,42,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,117310.979016,0
25,60,2,40,0,1658.37,5722.77,247.56,835.86,0,960,...,0,0,0,0,0,0,0,0,78390.810000,0
26,61,2,23,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,86262.210000,0
27,66,2,25,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,55568.100000,0
28,68,2,24,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,34880.280000,0
29,74,2,23,0,55.05,127.44,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,126815.970000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75990,151793,2,59,0,188.40,188.40,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,493063.920000,0
75991,151794,2,26,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,117310.979016,0
75992,151795,2,24,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,99424.170000,0
75993,151796,2,23,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,124660.680000,0
75994,151797,2,23,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,91768.500000,0
75995,151798,2,24,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,95812.860000,0
75996,151799,2,30,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,117310.979016,0
75997,151800,2,24,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,108712.860000,0
75998,151801,2,67,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,55648.980000,0
75999,151802,2,41,0,454.68,454.68,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,113833.620000,0
76000,151804,2,75,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,117310.979016,1
76001,151805,2,24,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,80566.980000,0
76002,151806,2,37,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,394687.350000,0
76003,151807,2,23,0,326.82,434.52,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,86886.120000,0
76004,151808,2,45,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,75678.420000,0
76005,151809,2,32,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,64250.460000,0
76006,151810,2,45,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,117310.979016,0
76007,151811,2,61,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,83667.150000,1
76008,151813,2,23,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,73056.000000,0
76009,151815,2,29,0,123.36,185.88,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,176712.420000,0
76010,151816,2,25,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,165616.320000,0
76011,151818,2,55,0,64.89,64.89,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,128887.380000,0
76012,151820,4,50,0,2.67,269.58,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,117310.979016,0
76013,151821,2,35,0,139.47,586.83,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,31405.080000,0
76014,151825,2,39,0,375.99,405.33,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,90214.170000,0
76015,151829,2,48,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,60926.490000,0
76016,151830,2,39,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,118634.520000,0
76017,151835,2,23,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,74028.150000,0
76018,151836,2,25,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,84278.160000,0
76019,151838,2,46,0,0.00,0.00,0.00,0.00,0,0,...,0,0,0,0,0,0,0,0,117310.979016,0

# Feature Engineering

In [3]:
preprocess_list = []

## Encode Label

In [4]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

#add columns for encoded label and then if we don't need original column
#that time we will can drop the original columns

data.head()

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,1,2,23,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,39205.170000,0
1,3,2,34,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,49278.030000,0
2,4,2,23,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,67333.770000,0
3,8,2,37,0,195,195,0,0,0,0,...,0,0,0,0,0,0,0,0,64007.970000,0
4,10,2,39,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,117310.979016,0

### 필요하면 여러 feature 들을 인코드한다.

## Scale/Normailze Features

In [5]:
#필요하면 여러개 feature들 노멀라이즈
from sklearn.preprocessing import scale

def feature_scaling (data):
    for i in data.columns:
        if i == "ID" or i == "TARGET":
            continue
        data[i] = scale(data[i])


feature_scaling(data)
#preprocess_list.append(feature_scaling)

/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)
/Library/Python/2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)

KeyboardInterrupt:

# Cross validatae by multi-class logarithmic loss

In [52]:
#가져다 쓰기 다른거  ROCAUC

#이건 샌프란
from sklearn.cross_validation import KFold
from sklearn import datasets
from sklearn.metrics import roc_auc_score



def rocauc_score(model, features, labels, num_folds = 5):
    kfolds = KFold(len(features), num_folds)
    
    total_score = 0.0
    
    for train_index, test_index in kfolds:
        train_features = features.iloc[train_index]
        test_features = features.iloc[test_index]
        train_labels = labels[train_index]
        test_labels = labels[test_index]
        
        model.fit(train_features, train_labels)
        prediction = model.predict_proba(test_features)
        
        
       
        nd = test_labels.get_values()
        pos_prediction = [x[1] for x in prediction]
        score = roc_auc_score(nd, pos_prediction)
        total_score = total_score + score
        
    total_score = total_score / num_folds
    
    return total_score

# Prediction

## Predict

In [ ]:
#from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import svm

feature_names = data.columns[1:370]
#배열로 넘김
label_name = "TARGET"
#컬럼 넘김

tree30_score = rocauc_score(RandomForestClassifier(n_estimators=30, n_jobs= -1), data[feature_names], data[label_name])
#svmsvc_score = rocauc_score(svm.SVC(), data[feature_names], data[label_name])
Logistic_score = rocauc_score(LogisticRegression(n_jobs =-1), data[feature_names], data[label_name])
#tree20_score = multiclass_logloss_score(RandomForestClassifier(n_estimators = 20, n_jobs= -1), data[feature_names], data[label_name])
#tree30_score = multiclass_logloss_score(RandomForestClassifier(n_estimators = 70, n_jobs= -1), data[feature_names], data[label_name])
#log_score = multiclass_logloss_score(LogisticRegression(n_jobs = -1), data[feature_names], data[label_name])

# score함수 만들어서 추가 . 

print("  tree 30 = %.5, svmSVC = %.5f" % (tree30_score, svmsvc_score))

# Submit

In [6]:
train = pd.read_csv("data/train.csv")
test = pd.read_csv("data/test.csv")
"""
for preprocess_function in preprocess_list:
    preprocess_function(train)
    preprocess_function(test)
"""

 
feature_names = data.columns[1:370]

label_name = "TARGET"

#model = RandomForestClassifier(n_estimators = 200, n_jobs= -1)
model = LogisticRegression(n_jobs = -1)
model.fit(train[feature_names], train[label_name])
prediction = model.predict_proba(test[feature_names])

p = [x[1] for x in prediction]


submit = pd.DataFrame(data = {'TARGET' : p}, index = test["ID"] )
submit.index.names = ["ID"]
#submit.columns = label_columns

submit

          TARGET
ID
2       0.497080
5       0.496723
6       0.496614
7       0.486467
9       0.494694
11      0.496164
12      0.495516
15      0.496621
16      0.492046
17      0.497002
19      0.491905
21      0.494131
22      0.497078
24      0.495124
27      0.489218
28      0.487927
30      0.496331
33      0.491549
35      0.497055
37      0.491535
38      0.495835
40      0.491549
41      0.495353
44      0.489243
46      0.493889
47      0.488435
48      0.491549
50      0.491549
52      0.491549
53      0.483615
...          ...
151772  0.488134
151773  0.491654
151776  0.467487
151777  0.496698
151780  0.488721
151781  0.492149
151782  0.491549
151784  0.496356
151785  0.491549
151786  0.491545
151788  0.491735
151789  0.471280
151790  0.495348
151791  0.491549
151803  0.493836
151812  0.492471
151814  0.496121
151817  0.486864
151819  0.490479
151822  0.494559
151823  0.497357
151824  0.492706
151826  0.482251
151827  0.497330
151828  0.493548
151831  0.497101
151832  0.489414
151833  0.487948
151834  0.491549
151837  0.491548

[75818 rows x 1 columns]

In [70]:
from time import strftime, localtime

current_time = strftime("%Y.%m.%d %H.%M.%S", localtime())

submit.to_csv("submit/%s.csv" % current_time)